### ISSUE TITLE
session list - created and updated columns produce identical values

### ISSUE THREAD

**Issue by uwuvalon** [Anaconda-Platform/ae5-tools#131]
I was working with someone earlier who ran into what might be a bug. They had noticed the created and updated columns from `session list` were identical.

edit: corrected typo in command

**Comment by JucaVaz** [comment]
Managed to reproduce this issue and is still present. 
Changed the name of the session and columns **created** and **updated** still the same and not updating the time.

**Comment by joshburt** [comment]
We've identified this as an AE5 issue and not one within the tools.  Internal ticket https://anaconda.atlassian.net/browse/AENT-7995 created to track and address.
