### ISSUE TITLE
Requests Auth method

### ISSUE THREAD

**Issue by AlbertDeFusco** [Anaconda-Platform/ae5-tools#20]
@mcg1969 I've implemented a requests auth object. This can be used as an alternative to Authorization Bearer tokens for REST APIs. If a user attempts to interact with API which has not been shared with them they get a 403. Would this be appropriate to add to ae5-tools?

https://gist.github.com/AlbertDeFusco/b923dae0feb5411281753335dc7ee9cb

Here'e an example of how it can be used.

```python
import requests
from ae5_tools import AE5Auth

auth = AE5Auth('<username>', '<password>')

res = requests.get('https://<deployment-url>/<endpoint>',
                   params=<parameters>,
                   auth=auth)
if res.ok:
    print(res.json())
```

**Comment by mcg1969** [comment]
Closing for now since we've figured out what to do here. We can certainly consider an auth refactor but it seems less urgent now.
