### ISSUE TITLE
Missing runtime deps in meta.yaml

### ISSUE THREAD

**Issue by timsnyder** [Anaconda-Platform/ae5-tools#48]
I just installed ae5-tools 0.3 into a fresh conda environment with:
```
conda create -n ae5-tools -c ae5-admin ae5-tools
```

And running `ae5 --help` I get complains about missing:
* `dateutil` fixed by installing `python-dateutil`
* `pandas`

After installing those, I was able to run `ae5 --help`.

Should you add `pandas` and `python-dateutil` to your runtime deps so that they are installed for ae5-tools?

**Comment by mcg1969** [comment]
@timsnyder as of version 0.3, `pandas` should _not_ be a requirement, but it looks like there are some lingering, non-optional imports I need to root out. I will verify python-dateutil as well. Thank you _very_ much for the report!
