### ISSUE TITLE
create ~/.ae5 on install

### ISSUE THREAD

**Issue by AlbertDeFusco** [Anaconda-Platform/ae5-tools#68]
since this directory now used to store dockerfile and condarc perhaps we should create a post-link script to create the directory and place necessary files for first run.

**Comment by mcg1969** [comment]
It's not clear why we should create it on install—why wouldn't it be sufficient to just put the files there on the first relevant run? I'd prefer not to use a post-link script if not necessary.

**Comment by AlbertDeFusco** [comment]
Yeah, copying the Dockerfile and condarc when login is run would be fine. I'd want people to get a chance to change them before having to run a full `project image` command.

**Comment by mcg1969** [comment]
That makes sense!

**Comment by bkreider** [comment]
Fixed by #93
