### ISSUE TITLE
Separate integration tests from unittests

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Platform/ae5-tools#97]
The integration tests are comprehensive, but they take a lot of time.  The tests should be separated and probably some of the integrations tests should be duplicated as unit tests with their external calls mocked.

**Comment by joshburt** [comment]
This is addressed as part of https://github.com/Anaconda-Platform/ae5-tools/pull/174
We now have _explicit_ splits for unit, integration, system, and load testing.
